version: '3.5'
services:
  butter:
    container_name: butter
    restart: always
    build: .
    ports:
      - '3000:3000'
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork